.PHONY: build test clean

build:
	cargo build --release

test:
	cargo test

clean:
	cargo clean

ebpf_program.o:
	# TODO: EXTEND: Compile eBPF C code with clang -O2 -target bpf
	# For now, this is a placeholder
	@echo "eBPF object file would be compiled here (requires clang + libbpf)"
