FROM golang:1.21-alpine

WORKDIR /app

COPY controller/go.mod controller/go.sum ./

RUN go mod download

COPY controller/ .

RUN go build -o sdn-controller ./cmd/sdn-controller

EXPOSE 8080 9090

CMD ["./sdn-controller"]
